services:
  main:
    container_name: SportsGym
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "${APPLICATION_PORT}:${CONTAINER_PORT}"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${EXPORT_DATABASE_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
    driver: local
